#include QMK_KEYBOARD_H
#if __has_include("keymap.h")
#    include "keymap.h"
#endif


/* THIS FILE WAS GENERATED!
 *
 * This file was generated by qmk json2c. You may or may not want to
 * edit it directly.
 */

const uint16_t PROGMEM keymaps[][MATRIX_ROWS][MATRIX_COLS] = {
    [0] = LAYOUT_unibody_split_3x5_3(KC_Q, KC_W, KC_F, KC_P, KC_B, KC_J, KC_L, KC_U, KC_Y, KC_SCLN, KC_A, KC_R, KC_S, KC_T, KC_G, KC_M, KC_N, KC_E, KC_I, KC_O, KC_Z, KC_X, KC_C, KC_D, KC_V, KC_K, KC_H, KC_COMM, KC_DOT, KC_QUOT, LALT_T(KC_ESC), LCTL_T(KC_TAB), LT(1,KC_ENT), LT(2,KC_SPC), RSFT_T(KC_BSPC), RGUI_T(KC_DEL)),
    [1] = LAYOUT_unibody_split_3x5_3(KC_GRV, KC_UNDS, KC_MINS, KC_LPRN, KC_LBRC, KC_RBRC, KC_RPRN, KC_EQL, KC_PLUS, KC_COLN, KC_1, KC_2, KC_3, KC_4, KC_5, KC_6, KC_7, KC_8, KC_9, KC_0, KC_EXLM, KC_AT, KC_HASH, KC_DLR, KC_PERC, KC_CIRC, KC_AMPR, KC_ASTR, KC_BSLS, KC_SLSH, KC_TRNS, KC_TRNS, KC_TRNS, KC_RSFT, KC_TRNS, KC_TRNS),
    [2] = LAYOUT_unibody_split_3x5_3(KC_F1, KC_F2, KC_F3, KC_F4, KC_F5, KC_INS, KC_HOME, KC_UP, KC_END, KC_PSCR, KC_F6, KC_F7, KC_F8, KC_F9, KC_F10, KC_BTN1, KC_LEFT, KC_DOWN, KC_RGHT, KC_BTN2, KC_F11, KC_F12, LCTL(KC_C), LCTL(KC_D), LCTL(KC_V), KC_CAPS, KC_PGUP, KC_NO, KC_PGDN, KC_PAUS, KC_TRNS, KC_TRNS, KC_LSFT, KC_TRNS, KC_TRNS, KC_TRNS)
};



#ifdef OTHER_KEYMAP_C
#    include OTHER_KEYMAP_C
#endif // OTHER_KEYMAP_C

#define _LAYER_0 0x00000001      // the default layer state code
#define _LAYER_1 0x00000001      // the layer 1 state code
#define _LAYER_2 0x00000002      // the layer 2 state code

// Light LED 0 when keyboard layer 0 is active
const rgblight_segment_t PROGMEM layer_0[] = RGBLIGHT_LAYER_SEGMENTS(
    {0, 1, HSV_RED}             // Light 1 LED, starting with LED 0
);
// Light LED 0 when keyboard layer 1 is active
const rgblight_segment_t PROGMEM layer_1[] = RGBLIGHT_LAYER_SEGMENTS(
    {0, 1, HSV_GREEN}            // Light 1 LED, starting with LED 0
);
// Light LED 0 when keyboard layer 2 is active
const rgblight_segment_t PROGMEM layer_2[] = RGBLIGHT_LAYER_SEGMENTS(
    {0, 1, HSV_BLUE}           // Light 1 LED, starting with LED 0
);
// Light LED 0 when CAPSLOCK is active
const rgblight_segment_t PROGMEM layer_capslock[] = RGBLIGHT_LAYER_SEGMENTS(
    {0, 1, HSV_PURPLE}          // Light 1 LED, starting with LED 0
);
 
// Now define the array of layers. Later layers take precedence
const rgblight_segment_t* const PROGMEM my_rgb_layers[] = RGBLIGHT_LAYERS_LIST(
    layer_0,
    layer_1,
    layer_2,
    layer_capslock
);

void keyboard_post_init_user(void) {
    // Enable the LED layers
    rgblight_layers = my_rgb_layers;
}

bool led_update_user(led_t led_state) {
    rgblight_set_layer_state(3, led_state.caps_lock);
    return true;
}

layer_state_t default_layer_state_set_user(layer_state_t state) {
    rgblight_set_layer_state(0, layer_state_cmp(state, _LAYER_0));
    return state;
}

layer_state_t layer_state_set_user(layer_state_t state) {
    rgblight_set_layer_state(1, layer_state_cmp(state, _LAYER_1));
    rgblight_set_layer_state(2, layer_state_cmp(state, _LAYER_2));
    return state;
}